services:
  postgresdb:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulse_board
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    external: true
